version: 2.0

jobs:
  "nodejs-4":
    docker:
      - image: circleci/node:4-stretch
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian stretch non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-6":
    docker:
      - image: circleci/node:6-stretch
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian stretch non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-8":
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian stretch non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-9":
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian stretch non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "nodejs-4"
      - "nodejs-6"
      - "nodejs-8"
      - "nodejs-9"
