version: 2.0

jobs:
  "nodejs-8":
    docker:
      - image: circleci/node:8-buster
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian buster non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-10":
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian buster non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-12":
    docker:
      - image: circleci/node:12-buster
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian buster non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

  "nodejs-13":
    docker:
      - image: circleci/node:13-buster
    steps:
      - checkout
      - run: wget -O - http://packages.tiepie.com/public.key | sudo apt-key add -
      - run: sudo bash -c 'echo "deb http://packages.tiepie.com/debian buster non-free" > /etc/apt/sources.list.d/packages.tiepie.com.list'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libtiepie-dev
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "nodejs-8"
      - "nodejs-10"
      - "nodejs-12"
      - "nodejs-13"
